package com.pattisian.zetta.bank_backend.transactions.enums;

public enum TransactionType {
    BILL_PAYMENT, INTERNAL_FUND_TRANSFER, EXTERNAL_FUND_TRANSFER, CASH_WITHDRAWAL, INTEREST_CREDIT, TIME_DEPOSIT_PAYOUT, TIME_DEPOSIT_OPENING, TIME_DEPOSIT_PRE_TERMINATION, CASH_DEPOSIT, INCOMING_WIRE, POS_PURCHASE, REVERSAL;
}
